### ISSUE TITLE
Worker health checks

### ISSUE THREAD

**Issue by hlascelles** [que-rb/que#260]
We are deploying que workers in our Kubernetes environments, and would like to add [Liveness and Readiness checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).

We've had a few ideas, including something as simple as the worker writing a file to disk when it is "ready" which can be looked for, or an embedded sinatra app that can be curled from inside the container (to avoid opening up ports) thus:

```
readinessProbe:
  exec:
    command: ["curl", "--silent", "--show-error", "--fail", "http://localhost:8080/health"]
  initialDelaySeconds: 10
  periodSeconds: 5
```

Beyond that it gets more complicated. How to tell between a hung worker and one that is processing a very long task etc...

How are others handling this issue?
